Add example for question/answers to FB lead int
lassodatasystems/registrant-submitter-php pull request #17
Opened 2017-01-24 02:21 UTC by tutfoo

2017-01-25 17:17 UTC, aclarkd requested changes

2017-01-25 17:17 UTC, aclarkd commented on src/registrant-submitter-zapier.py
> +    'questions': [
Thanks for keeping this up to date.

We should also include how to use question ids and answer ids

2017-01-25 21:34 UTC, tutfoo commented on src/registrant-submitter-zapier.py
> +    'questions': [
Good call, I've added that in this commit: https://github.com/lassodatasystems/registrant-submitter-php/pull/17/commits/67bdb5f61a58ebe61f9223888dcf25f50a783af5

2017-02-02 17:01 UTC, aclarkd approved these changes

2017-02-02 17:01 UTC, merged